# Generated by Django 4.0 on 2021-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
