# Generated by Django 4.0 on 2021-12-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='data',
        ),
    ]
